new Vue({
    el:"#app",
    data:{
        con:[
            {id:1,
                title:'123'},
            {
                id:2,
                title:'456',
            },
            {
                id:3,
                title:'789',
            },
            {
                id:4,
                title:'2546',
            },
        ],
        status:false,
        conner:'',
    },
    methods:{
            aa(){
                this.status=true;
            },
            bb(val){
                this.conner=val;
                this.status=false;
            },
     }
})